### PR TITLE
data is also an interpolation ref in Terraform 0.7

### PR DESCRIPTION
**Pull request by nanoz**

### CODE REVIEW

**Comment by wholroyd** [comment]
@nanoz - Sorry for invalidating your PR, I realized I didn't have the last change pushed. Apologies. Before we fix that though...

@commarla @nanoz - I originally did just `var` and `module` because those are two system keywords for Terraform that isn't declared by a user. Otherwise, it would have just been a resource reference, which didn't hold any special meaning to Terraform, and because I didn't want to determine what all of the possible resource names were in the ecosystem.

I originally developed the extension for Terraform and then later made it more flexible to handle the HCL language itself and not be so specific. Or if I did, I would eventually do it in file extension specific code in the extension. For example `var` and `module` should only have meaning in .tf files, but not Otto's Appfile. This syntax for the two words is left over from the original direction.

I'm starting to think that it might be better to mark the first octet in the string as the variable that is being accessed as opposed to looking for certain keywords. I think it would solve both of the issues you've raised and take the extension back to being neutral syntax wise. I would assume it would make more sense in that regard because then the convention is `[object](.[property])+`.

What are your thoughts?

**Comment by commarla** [comment]
Hi @wholroyd ,

I agree with you. In fact in terraform 0.7 "terraform_remote_state" will be preceded by "data" (Using it in a ressource is deprecated)

As you can see in this screenshot : https://infinit.io/_/yVaJjXG

For now I only use terraform and I am not aware of the behavior of other products using HCL.

Regards,

**Comment by wholroyd** [comment]
Sounds good, I'll make the change this weekend if I can.

**Comment by nanoz** [comment]
I kind of liked the fact that having explicit keywords easily showed syntax errors. I agree it strongly binds to the Terraform syntax though.

**Comment by wholroyd** [comment]
Sorry for the delay in getting the fix in, haven't had time until now. This will be fixed in v0.0.5.

**Pull request closed without merging**
